modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"
[[mods]]
modId="kakapos"
version="0.1.0-1.20"
displayName="Kakapos"
logoFile="icon.png"
credits="Thanks to the amazing community at the Odd Water Mobs discord server."
authors="Jocosero"
description='''
A simple mod that adds the kakapo parrot to the jungle biome!
'''
[[dependencies.kakapos]]
modId="forge"
mandatory=true
versionRange="[41,)"
ordering="NONE"
side="BOTH"
[[dependencies.kakapos]]
modId="forge"
mandatory=true
versionRange="[41,)"
ordering="NONE"
side="BOTH"
[[dependencies.kakapos]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"